stages:
- stage: 
  dependsOn: Build 
  displayName: PR Review
  condition:  and(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/master'))
  jobs:
    - deployment: Set_Status_Preview
      environment: Preview 
      displayName: Set Status Preview (Destroy) 
      variables:
        PREVIEW_STATUS: destroy 
      pool:
        vmImage: $(vmImageName)

      strategy:
        runOnce:
          deploy:
            steps: 
            - template: ../steps/set-commit.yml
            - checkout: CamsServerDeployment
            - task: CmdLine@2
              displayName: Set PREVIEW_NAME
              inputs:
                script: |
                  PREVIEW_NAME=`echo $(System.PullRequest.SourceBranch) | sed "s/\//-/g" | sed "s/refs-heads-//"`
                  echo "##vso[task.setvariable variable=PREVIEW_NAME]$PREVIEW_NAME"

                  echo "Current Preview: $(PREVIEW_NAME)"
            - template: ../steps/replace-token.yml  # Sets preview status label in each manifest
              parameters: 
                environment: preview

            - task: Kubernetes@1
              displayName: kubectl apply deployment/cams-api.yml
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'Preview'
                namespace: 'preview'
                command: 'apply'
                useConfigurationFile: true
                configuration: '$(System.DefaultWorkingDirectory)/preview/deployments/cams-api.yml'
                useClusterAdmin: true

            - task: Kubernetes@1
              displayName: kubectl apply deployment/mysql.yml 
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'Preview'
                namespace: 'preview'
                command: 'apply'
                useConfigurationFile: true
                configuration: '$(System.DefaultWorkingDirectory)/preview/deployments/mysql.yml'
                useClusterAdmin: true

            - task: Kubernetes@1
              displayName: kubectl apply services/cams-api.yml
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'Preview'
                namespace: 'preview'
                command: 'apply'
                useConfigurationFile: true
                configuration: '$(System.DefaultWorkingDirectory)/preview/services/cams-api.yml'
                useClusterAdmin: true 

            - task: Kubernetes@1
              displayName: kubectl apply services/mysql
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'Preview'
                namespace: 'preview'
                command: 'apply'
                useConfigurationFile: true
                configuration: '$(System.DefaultWorkingDirectory)/preview/services/mysql.yml'
                useClusterAdmin: true 