export const cssClassName = {
  JERA_LIKE_ICON_CLASS: 'color-green-60 jera-like-1',
  JERA_DISLIKE_ICON_CLASS: 'color-red-60 jera-dislike',
  JERA_STABLE_ICON_CLASS: 'jera-stable-1 color-grey-blue-70',
  JERA_LAMP_CHARGE: 'jera-lamp-charge',
  JERA_GRAPH: 'jera-graph',
  JERA_STATUS: 'jera-status',
  JERA_BUILDING_4: 'jera-building-4',
  JERA_HOME_TREND_UP: 'jera-home-trend-up',
  JERA_ARROW_DOWN_1: 'jera-arrow-down-1',

  TOOLTIP_CONTENT: 'tooltip-content',
  TOOLTIP_HEADER: 'tooltip-header',
  TOOLTIP_PERIOD_SECTION: 'tooltip-period-section',
  TOOLTIP_NAME_SECTION: 'tooltip-name-section',
  TOOLTIP_BOTTOM: 'uk-tooltip-bottom-custom',
  TOOLTIP_TOP_POSITION: 'uk-tooltip-top uk-tooltip-top-custom',
  TOOLTIP_CUSTOM: ' uk-tooltip-cutom',
  TOOLTIP_TOP: 'uk-transdorm-origin-center-top uk-tooltip-top-center uk-transform-origin-center-top',
  COLOR_LABEL: 'color-label',
  CUSTOM_TOOLTIP: 'uk-tooltip-bottom-custom uk-tooltip-cutom text-highlight',
  TEXT_HIGHLIGHT: 'text-highlight',
  BG_GREY_BLUE_40_A10: 'bg-grey-blue-40-a10',
  COLOR_GREEN_60: 'color-green-60',
  COLOR_RED_60: 'color-red-60',
  COLOR_GREY_BLUE_70: 'color-grey-blue-70',
  COLOR_GREY_BLUE_60: 'color-grey-blue-60',
  COLOR_GREY_BLUE_80: 'color-grey-blue-80',
  COLOR_GREY_BLUE_95: 'color-grey-blue-95',
  COLOR_WHITE: 'color-white',
  MB_20:'mb-20'
}
